### ISSUE TITLE
Range of fluid intake is strange

### ISSUE THREAD

**Issue by Snownee** [CD4017BE/InductiveLogistics#10]
Hi, I test fluid intake at the range of 5, expecting to clear a regular cube, and here are the final results:
![2018-01-17_16 22 17](https://user-images.githubusercontent.com/16059084/35032946-d9a9770e-fba3-11e7-849c-278238446c51.png)
![2018-01-17_16 28 01](https://user-images.githubusercontent.com/16059084/35032948-d9e10a5c-fba3-11e7-83a4-74b726005e57.png)
Every time the result is different, so here are two possible results.

Version 1.1.1
Forge 14.23.1.2583

**Comment by CD4017BE** [comment]
That's because in addition to the cube range limit, the device also only has a limited amount of path nodes to find the fluid blocks. By default this is 3 x range so in a clean area with no obstacles every block should be reachable. Here eventually the pipes and the tank may have been an obstacle.

However there is a config-option called `fluid_io_path` that allows you to change the path length.
If you increase it to a value of 4 or 5 the cube should be drained cleanly. When operating with such small areas you can probably even set it to much much higher values without noticeable performance impacts.
