### ISSUE TITLE
Item pipes have weird behavior

### ISSUE THREAD

**Issue by brisingraerowing** [CD4017BE/InductiveLogistics#17]
### What I did:
I was trying to link one input to three outputs, but the pipe directions went all wonky as I placed them.

### What happened:
Item Transport Pipes always point to the first insertion pipe placed, even if there are others.

### What should have happened:
The item transport pipes should point from extraction pipes to insertion pipes.

### Used Versions:
- Minecraft-1.12.2
- InductiveLogistics-1.1.3
- CD4017BE_lib-6.2.1
- Forge-14.23.2.2627

(Screenshot is a partial setup)
![2018-03-16_12 46 44](https://user-images.githubusercontent.com/250409/37533574-9a6c1fe0-2918-11e8-8749-eef5eca08234.png)

**Comment by CD4017BE** [comment]
Extraction / Injection Pipes each must be connected to at least one inventory in order to provide a source / destination point for the transport path. The three extraction pipes in your setup aren't.

If you want to split one input on both coke-ovens, because transport pipes can't branch, the left injection pipe needs to be connected directly to the right injection pipe (via transport pipes) which is then connected to your item supply inventory (via transport pipes and finally extraction pipe).

However, in the [new version](https://github.com/CD4017BE/InductiveLogistics/releases/tag/v1.2.0) that was just released, some new features were added that provide better path control and branching.
