### ISSUE TITLE
Server Crash w/ Fluid Extractor

### ISSUE THREAD

**Issue by nathantfaust** [CD4017BE/InductiveLogistics#21]
I am reporting this along with an issue report posted on the SevTech Ages issue tracker. Please refer to this link: https://github.com/Darkosto/SevTech-Ages/issues/2219

### What I did:
Fluids were pumping into a buffer before being pumped into another machine
### What happened:
The pipes stopped moving fluid out of the tank and server crash with a null pointer exception related to ticking the fluid extractor.

### What should have happened:
The system should have maintained its function as it was working previously without any changes to the mechanism.

### Used Versions:
- Minecraft-1.12.2
- InductiveLogistics-1.1.3
- CD4017BE_lib-?.?.?
- Forge-14.23.2.2651
- Carry On
- set by SevTech Modpack

**Comment by CD4017BE** [comment]
The described issues definitely match some bugs I fixed in 1.2.0 and finally [1.2.1](https://github.com/CD4017BE/InductiveLogistics/releases/tag/v1.2.1)

These bugs involved networks of the Advanced Universal Pipes sometimes getting into invalid states after chunk (or World) unloading and reloading. These then caused all sorts of problems from the pipes not working anymore, entire loss of attached connectors and filters, up to sometimes pipe connectors being ticked although they weren't part of the network anymore causing the above mentioned crash.

The pipe network has been greatly redesigned now to ensure that these invalid states don't happen anymore and to make ticking of components without network impossible.
