### ISSUE TITLE
Advanced Universal Pipes

### ISSUE THREAD

**Issue by madkingdiamond** [CD4017BE/InductiveLogistics#31]
### What I did:
Tried using the Advanced Universal pipes with fluids for the instant fluid transport.

### What happened:
Advanced Universal pipes would not connect to any other pipe. Fluid or item.

### What should have happened:
Should have connected to the other pipes like what I've seen by others using them
### Used Versions:
- Minecraft-1.12.2
- InductiveLogistics-1.2.3
- CD4017BE_lib-6.2.4
- Forge-2.4.2.58
- _other installed mods: SevTech 3.0.8
- _relevant changes to config: None

Picture of them not connecting vvv
https://gyazo.com/fa878d1f5c08cae9c41b09fdc4ca7453

**Comment by CD4017BE** [comment]
They are not supposed to connect, at least not directly.

For the advanced Universal pipes to do anything: Extraction, Injection, Source or Destination Pipes need to be attached to the sides of such a pipe (as stated in the tooltip) which is done by right-click on the pipe with the item in hand.

The way Advanced Universal Pipes can interact with normal Transport Pipes is, that Transport Pipes have an internal inventory (or fluid tank) where the Universal Pipe can put things in or pull things out. And Universal Pipes also mark themselves as source or destination (depending on type of attached pipe connection) for the Transport Pipe's path finding as a convenience so that no extra Source or Destination Pipe is required.
