### ISSUE TITLE
[Request] Configurable Fluid input/extract in mB for compatibility with Inspirations Cauldrons

### ISSUE THREAD

**Issue by Dragnier** [CD4017BE/InductiveLogistics#39]
The Inspirations mod by KnightMiner has a Better Cauldrons module which changes how they work and allows for some automation within it's own mod by enabling dispensers to fill them. However, it would be nice to have pipes that can do that as a player progresses into better tech levels.

The issue is that the cauldron changes only allow fluid transfer in 250 mB amounts up to one bucket. Most pipes transfer at less or more than this and therefore do not work with the mod. It would be nice to see a configuration option on your fluid pipes that allows their transfer rate to be set. Or perhaps even a special pipe that allows the transfer rate to be changed using an in-game GUI.

**Comment by CD4017BE** [comment]
That feature already exists, see `/config/cd4017be/inductiveLogistics.rcp`:
```
!internal capacity of fluid pipes
fluid_pipe_cap = 1000;
```
The pipe capacity is at the same time its maximum transfer rate per operation cycle (which is also configurable).

Alternatively there is also ingame the `Amount Filter` that lets you set/limit the rate of extraction pipes and since individual fluid packets don't stack within the pipe, extracting at 250mB/op will also make it come out in 250mB packets at the other end.
