### ISSUE TITLE
Pipes break when unloaded

### ISSUE THREAD

**Issue by flamechair** [CD4017BE/InductiveLogistics#9]
Hi,

I've noticed a few times that when I leave my pipe setup without a chunk loader, that the pipes stop working. They stop processing fluids/items until you break and replace them. If they are accompanied by a chunk loader, this issue does not happen.

Minecraft: 1.12.2
Forge: 14.23.1.2555
IL: 1.0.4

**Comment by flamechair** [comment]
Also I've been using the covering system to disguise parts of the pipe as normal blocks, not sure if that has anything to do with it.

**Comment by CD4017BE** [comment]
Usually when a chunk next to the pipe is loaded again and that neighboring block inside the newly loaded chunk has a TileEntity (e.g it's a pipe machine or whatever) or if the pipe itself is loaded it should receive an update event that tells it to refresh it's cached references to neighboring machines or pipes and continue operating (The caching is done to boost performance because asking the world for block/TileEntity data is quite computationally expensive when doing it every tick).

I think the problem appears when the pipe ignores that event due to another neighboring chunk that's still unloaded and the remaining chunk, when it loads has no neighbor TileEntity to cause another update.

_Classical chunk loading bugs in modded Minecraft :)_
